---
- hosts: cloudport
  become: yes
  tasks:
    - name: Import Docker repo key
      apt_key: keyserver=p80.pool.sks-keyservers.net
               id=58118E89F3A912897C070ADBF76221572C52609D
               state=present
    - name: Add Docker repo
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'
                      state=present update_cache=yes
    - name: Install Docker
      apt: name=docker-engine state=latest
      notify:
        - Reload Docker
    - name: Ensure Docker enabled and started
      service: name=docker enabled=yes state=started
  handlers:
    - name: Reload Docker
      service: name=docker state=reloaded
